Set JAVA_HOME the right way

diff --git a/flume-package/src/main/resources/init.d/deb/flume-ng b/flume-package/src/main/resources/init.d/deb/flume-ng
--- a/flume-package/src/main/resources/init.d/deb/flume-ng
+++ b/flume-package/src/main/resources/init.d/deb/flume-ng
@@ -17,11 +17,11 @@ set -e
 # Source function library.
 . /lib/lsb/init-functions
 
+# Source default
+. /etc/default/flume-ng
+
 # Set sensible defaults
 LOG_PATH=/var/log/flume
-# NOTE:  flume references java from JAVA_HOME, so this is configured differently than the repose
-# init script.
-export JAVA_HOME=/usr/lib/jvm/jre-1.7.0-openjdk.x86_64
 CONFIG_DIRECTORY=/opt/flume/conf
 COMMAND=/opt/flume/bin/flume-ng
 USER=flume
@@ -30,7 +30,7 @@ DAEMON_HOME=/opt/flume
 PID_FILE=/var/run/${NAME}.pid
 START_ARGS="--start --quiet --oknodo --make-pidfile --pidfile ${PID_FILE} --background"
 RUN_ARGS="agent -n repose-agent -c $CONFIG_DIRECTORY -f $CONFIG_DIRECTORY/cf-flume-conf.properties"
-# NOTE:  flume declares its JVM arguments in /opt/flume/conf/flume-env.sh, not here
+# NOTE: flume declares its JVM arguments in /opt/flume/conf/flume-env.sh, not here
 
 # Can override the defaults in /etc/sysconfig
 . /etc/sysconfig/flume-ng
@@ -48,6 +48,11 @@ fi
 if [ ! -d $LOG_PATH ]; then
   echo "Unable to log to $LOG_PATH."
   exit 1
+fi
+
+if [ ! -d $JAVA_HOME ]; then
+    echo "Could not find JAVA_HOME. Please set JAVA_HOME in /etc/default/flume-ng or your shell environment."
+    exit 1
 fi
 
 start()
